### ISSUE TITLE
Retire `javiche` in favor of `agjax`? 

### ISSUE THREAD

**Issue by jan-david-fischbach** [mfschubert/agjax#4]
Hey @mfschubert,
have you seen [`javiche`] (https://github.com/Jan-David-Black/javiche)? It was initially intended to wrap ceviche in jax, but can basically do any autograd differentiable function.
Would you be willing to add some docs and publish to pypi and conda (if you want I can help with that)? I would then retire `javiche`, as it is less general compared to `agjax` (in that it for example has ceviche as an install dependency).
Regards JD

**Comment by mfschubert** [comment]
Hi @Jan-David-Black, yes I have seen `javiche`, and I think we recognized the same need. :-)

I am planning on adding more docs, and actually an example that exercises inverse design using the ceviche challenges. I haven't published a package to pypi or conda, so I would absolutely appreciate collaboration. I only have time sporadically to work on this but would expect things to be in a releasable state within a few weeks.

**Comment by mfschubert** [comment]
Closing this since @jan-david-fischbach took care of this in https://github.com/mfschubert/agjax/pull/9
